version: "3.9"
networks:
  main:
    name: main
services:
  connect:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONNECT_CERT_PATH_BUILD_ARG: ./local-config/connect
        CONNECT_CONFIG_PATH_BUILD_ARG: ./local-config/connect
    profiles: ["deployment"]
    networks:
      - main
    image: linuxforhealth/connect:0.42.0
    environment:
      CONNECT_CA_PATH: /usr/local/share/ca-certificates
      IPFS_CLUSTER_URI: http://ipfs-cluster-0:9099
    ports:
      - "5000:5000"
  nats-server:
    networks:
      - main
    image: docker.io/linuxforhealth/jetstream:v0.0.19
    volumes:
      - ./local-config/nats:/conf
    command: server --config=/conf/nats-server.conf
    ports:
      - "4222:4222"
  zookeeper:
    networks:
      - main
    image: docker.io/linuxforhealth/zookeeper-alpine:3.6.2
  kafka:
    networks:
      - main
    image: docker.io/linuxforhealth/kafka-alpine:2.5.0
    restart: "always"
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  ipfs-cluster-0:
    container_name: ipfs-cluster-0
    networks:
      - main
    image: linuxforhealth/ipfs-cluster:v0.14.0
    depends_on:
      - ipfs-node-0
    environment:
      CLUSTER_PEERNAME: ipfs-cluster-0
      CLUSTER_SECRET: 724931756d306e6d56685055714966347373424e77484d733369575433364d42
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs-node-0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9099 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      - "9099:9099"
    volumes:
      - ./local-config/ipfs/volumes/ipfs-cluster-0/config:/data/ipfs-cluster
  ipfs-node-0:
    container_name: ipfs-node-0
    networks:
      - main
    image: linuxforhealth/go-ipfs:release-v0.9.1
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"
    environment:
      LIBP2P_FORCE_PNET: '1'
    volumes:
      - ./local-config/ipfs/volumes/staging_dir:/export
      - ./local-config/ipfs/volumes/pv-data_dir:/data/pv
      - ./local-config/ipfs/volumes/ipfs-node-0:/data/ipfs
      - ./local-config/ipfs/private-ipfs-network/swarm.key:/data/ipfs/swarm.key
      - ./local-config/ipfs/private-ipfs-network/init.sh:/usr/local/bin/start_ipfs
  ibm-fhir:
    profiles: ["fhir", "deployment"]
    networks:
      - main
    image: docker.io/ibmcom/ibm-fhir-server:4.4.0
    ports:
      - 9443:9443
  fabric-client:
    profiles: ["fabric"]
    networks:
      - main
    image: linuxforhealth/fabric-client:0.1
    restart: "always"
    environment:
      INITIALIZE_WITH_DISCOVERY: 'false'
      DISCOVERY_AS_LOCALHOST: 'false'
    volumes:
      - ./local-config/fabric/conf:/usr/src/app/conf
    ports:
      - "9043:9043"
